### ISSUE TITLE
Question: What's the state of Lazer? Any plans to continue development?

### ISSUE THREAD

**Issue by DanJFletcher** [photonstorm/lazer#18]
Just wondering if Lazer is still active or not. Recently played around with Phaser just to try out a JS game framework, but I _really_ like the idea of using ES2015 and components. 

Thanks in advance if anyone gets back to me!

**Comment by photonstorm** [comment]
Everything I ever wanted to do with Lazer, with the exception of using ES6, is being done in Phaser v3. The modules, components structure, new renderer, new features, etc is all in v3, and is being actively worked on full-time. See the Phaser World newsletter for weekly updates.

Once v3 is out, has settled down, and gone through a few versions, that will be a good time to revisit ES6. Until that point, no development will take place on this repo.

**Comment by bentok** [comment]
Babel compiles es6 modules to the same commonjs modules that Phaser v3 is using. Is there a particular reason why v3 and Lazer are going to be different libraries in the end?

**Comment by photonstorm** [comment]
Just to say that this discussion is covered in detail here:

https://www.patreon.com/posts/evolution-of-3-7547955

or on the Phaser Forum here: http://www.html5gamedevs.com/topic/27224-the-evolution-of-phaser-3-and-lazer/

Please redirect all responses there, thanks.
