### ISSUE TITLE
Does Lazer has relative with Pixi ?

### ISSUE THREAD

**Issue by nvcken** [photonstorm/lazer#2]
Does Lazer like Phaser built on top Pixi or is a standalone framework ?

**Comment by northducks** [comment]
http://www.html5gamedevs.com/topic/11783-phaser-3-development-log-we-jan-16th/?p=68025

**Comment by nexiuhm** [comment]
Standalone, with it's own renderer.

**Comment by photonstorm** [comment]
It's not built on-top of Pixi, no. It's not built on-top of any renderer actually. Questions like this are best asked on the mailing list please (or the forum)

**Comment by hayesmaker** [comment]
seems like a valid place to ask questions to me... https://github.com/photonstorm/lazer/labels
