### ISSUE TITLE
Adapt Lazer to UMD for use with bundlers.

### ISSUE THREAD

**Issue by willcode4food** [photonstorm/lazer#6]
I think it would be beneficial to update Lazer to be used as a [Universal Module Definition](https://github.com/umdjs/umd) (UMD) compliant NPM library.  This would make it so the library could be available on NPM for consumption.  Lazer could also take advantage of modular development using tools like [Browserify ](http://browserify.org/) or [Webpack](https://webpack.github.io/).   Developers could take advantage of [optimizations](http://webpack.github.io/docs/optimization.html) from webpack such as code splitting, and chunking.

**Comment by photonstorm** [comment]
Are we still able to use ES6 modules (like we've been doing so far) within the code, and still support UMD?

**Comment by photonstorm** [comment]
Sorry I should have checked your branch before asking - am I right in thinking that all that really needs to change is that the import paths become relative, and that all functions that export are given names? (something I've been trying to do recently anyway, but I think lots of early ones don't)

If that's the case then i'm all for this.

**Comment by willcode4food** [comment]
Yeah, so looking into this more I realized UMD may not be the way to go.  Working through this I am realizing that all we really need is ES6 modules formatted in the way you described.  I think I'll kill the branch I am working on and work towards properly formatted ES6 modules.
